### ISSUE TITLE
Question rather than an Issue, Example of dynamic multi sorting

### ISSUE THREAD

**Issue by AsuraKev** [Drizin/InterpolatedSql#5]
Hi there,

Sorry couldnt find a place to place a Q&A, how can we do dynamic multi sorting using this library?

e.g

var sorting = 'ORDERBY a DESC, b ASC, c DESC';

var q = cn.QueryBuilder($@"
    SELECT ProductId, Name, ListPrice, Weight FROM Product 
    WHERE ListPrice <= {maxPrice}
   {sorting}");

will this be prone to SQL injection?

thanks

**Comment by Drizin** [comment]
That would generate this SQL (which is invalid):
```SELECT ProductId, Name, ListPrice, Weight FROM Product
WHERE ListPrice <= @p0
@p1```
So you probably want to use the "raw" modifier, like this: `{sorting:raw}`. Note that this will just pass that raw variable to the SQL statement, so yes - if "sorting" variables come from the user (like a query string) it should be manually sanitized (or tested against forbidden characters) to avoid a SQL injection.

**Comment by AsuraKev** [comment]
thanks for the reply! how about tweak an example from the doc like below

from this 
![image](https://github.com/Drizin/InterpolatedSql/assets/52765572/788c614f-03d3-49cd-8ad6-005d748f1909)

to

var orderByClause = $"ORDER BY ProductId ASC,  ColumnB DESC";
q+= $"{orderByClause }"

wouldnt this be SQL injection proof as well?

**Comment by Drizin** [comment]
The same thing I've said before still holds true in this example:

If you interpolate ANY variable without the raw modifier, that will be translated into a Sql Parameter (which is not valid for a ORDER BY clause). It doesn't make any difference if the interpolation happens right in the constructor, or if it happens later by calling `Append()` or just by using the `+=` operator. All those options will just get the interpolated string and will make it a parameter (`@p0`, etc). 

So yes, you can use `q += $"{orderByClause:raw}". Or you can also do `q.AppendLiteral(orderByClause)`, which is pretty much the same. But in both cases you're just appending a string (not parametrized) to your SQL statement, so in both cases the string should be safe/validated.

**Comment by AsuraKev** [comment]
thanks!  so apart from doing sanitization upfront, are there any other good options to construct dynamic sorting clause?  :)

**Comment by Drizin** [comment]
I don't think so. This library only helps with the creation of SqlParameters, which is not what you need here. You're still generating a SQL clause (in plain string), so it needs to be safe. 

Validating "free text input" (like a username) against SQL injection is not so trivial (because there are multiple tricks to escape from a literal), but for your case which is just validating an ORDER BY clause it should be **much simpler**:
- If you get a list of columns you can just test if the column names are valid (if they belong to your table)
- If you get the whole order by clause as a string you can just test if it doesn't contain any special dangerous characters. Probably you should only accept `A-Z`, `a-z`, `0-9`, `,` (comma), ` ` (space). By sticking to those characters you'll be certainly safe.
